sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.test -t theolib/uws .

script:
  - docker run theolib/uws python -m unittest discover ./tests

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  name: uws
  application: "uws"
  env: "Uws-env"
  bucket_name: "elasticbeanstalk-us-east-2-758241873697"
  bucket_path: "uws"
  on:
    branch: master
  access_key_id:  "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"