version: '3'
services:
  uws_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8050:8050"
    volumes:
      - .:/app
  uws_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    command: ["python", "-m", "unittest", "discover", "./tests"]